In [84]:
import pandas as pd
import numpy as np

In [ ]:
data=[
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
    
]
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [58]:
df=pd.DataFrame(data, columns=columns)

In [59]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [69]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    # ...
]

In [70]:
df=pd.DataFrame(data, columns=columns)

In [71]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [73]:
df.Make

0     Nissan
1    Hyundai
Name: Make, dtype: str

In [74]:
df['Engine HP']

0    138.0
1      NaN
Name: Engine HP, dtype: float64

In [75]:
df[['Make', 'Model', 'MSRP']]

      Make   Model   MSRP
0   Nissan  Stanza   2000
1  Hyundai  Sonata  27150

In [76]:
df['id']=[1, 2, 3, 4, 5]

ValueError: Length of values (5) does not match length of index (2)

In [77]:
del df['id']

KeyError: 'id'

In [78]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [79]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [83]:
df.index=['a', 'b', 'c', 'd', 'e']
df

ValueError: Length mismatch: Expected axis has 2 elements, new values have 5 elements

In [ ]:
df.iloc[[1, 2, 4]]

AttributeError: 'function' object has no attribute 'iloc'

In [ ]:
df=df.reset_index

AttributeError: 'function' object has no attribute 'reset_index'

In [ ]:
df = df.reset_index(drop=True)
df['Engine HP'] * 2

AttributeError: 'function' object has no attribute 'reset_index'