In [253]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [254]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'
!wget $data -O data-week-3.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.

In [255]:
import pandas as pd

#data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'
#df = pd.read_csv(data)

# عرض أبعاد الجدول (عدد الصفوف والأعمدة)
#print("Shape:", df.shape)

# استعراض أول 5 صفوف
#df.head()

In [256]:
df = pd.read_csv('data-week-3.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [257]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [258]:

df.head().T

,0,1,2,3,4
customerid,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
seniorcitizen,0,0,0,0,0
partner,Yes,No,No,No,No
dependents,No,No,No,No,No
tenure,1,34,2,45,2
phoneservice,No,Yes,Yes,No,Yes
multiplelines,No phone service,No,No,No phone service,No
internetservice,DSL,DSL,DSL,DSL,Fiber optic
onlinesecurity,No,Yes,Yes,Yes,No
onlinebackup,Yes,No,Yes,No,No
deviceprotection,No,Yes,No,Yes,No
techsupport,No,No,No,Yes,No
streamingtv,No,No,No,No,No
streamingmovies,No,No,No,No,No
contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
paperlessbilling,Yes,No,Yes,No,Yes
paymentmethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,No,No,Yes,No,Yes

In [259]:
tc = pd.to_numeric(df.totalcharges, errors='coerce')

In [260]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')
df.totalcharges = df.totalcharges.fillna(0)
df.churn.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: churn, dtype: str

In [261]:
df[tc.isnull()][['customerid', 'totalcharges']]

      customerid  totalcharges
488   4472-LVYGI           0.0
753   3115-CZMZD           0.0
936   5709-LVOEQ           0.0
1082  4367-NUYAO           0.0
1340  1371-DWPAZ           0.0
3331  7644-OMVMY           0.0
3826  3213-VVOLG           0.0
4380  2520-SGTTA           0.0
5218  2923-ARZLG           0.0
6670  4075-WKNIU           0.0
6754  2775-SEFEE           0.0

In [262]:
df.churn = (df.churn == 'yes').astype(int)
from sklearn.model_selection import train_test_split
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [263]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [264]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

del df_train['churn']
del df_val['churn']
del df_test['churn']

In [265]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')
df.totalcharges = df.totalcharges.fillna(0)

In [266]:
df.churn.head()

0    0
1    0
2    0
3    0
4    0
Name: churn, dtype: int64

In [267]:
df.churn = (df.churn == 'yes').astype(int)

In [268]:
from sklearn.model_selection import train_test_split

In [269]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [270]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [271]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [272]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [273]:
df_full_train = df_full_train.reset_index(drop=True)

In [274]:
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [275]:
df_full_train.churn.value_counts(normalize=True)

churn
0    1.0
Name: proportion, dtype: float64

In [276]:
df_full_train.churn.mean()

np.float64(0.0)

In [277]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']
categorical = [
    'gender',
    'seniorcitizen',
    'partner',
    'dependents',
    'phoneservice',
    'multiplelines',
    'internetservice',
    'onlinesecurity',
    'onlinebackup',
    'deviceprotection',
    'techsupport',
    'streamingtv',
    'streamingmovies',
    'contract',
    'paperlessbilling',
    'paymentmethod',
]

In [278]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [279]:
global_churn = df_full_train.churn.mean()

In [280]:
churn_female = df_full_train[df_full_train.gender == 'female'].churn.mean()
churn_male = df_full_train[df_full_train.gender == 'male'].churn.mean()

In [281]:
global_churn - churn_female

np.float64(nan)

In [282]:
global_churn - churn_male

np.float64(nan)

In [283]:
df_full_train.partner.value_counts()

partner
No     2932
Yes    2702
Name: count, dtype: int64

In [284]:
churn_partner = df_full_train[df_full_train.partner == 'yes'].churn.mean()
churn_no_partner = df_full_train[df_full_train.partner == 'no'].churn.mean()

In [285]:
churn_partner     = 0.20503330866025166
churn_no_partner  = 0.3298090040927694

In [286]:
churn_no_partner / global_churn

C:\Users\EBIHA10\AppData\Local\Temp\ipykernel_35680\1074788301.py:1: RuntimeWarning: divide by zero encountered in scalar divide
  churn_no_partner / global_churn

np.float64(inf)

In [287]:
# SELECT
    # gender,
    # AVG(churn),
    # AVG(churn) - global_churn AS diff,
    # AVG(churn) / global_churn AS risk
# FROM
    # data
# GROUP BY
    # gender;

In [288]:
from IPython.display import display

for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_churn
    df_group['risk'] = df_group['mean'] / global_churn
    display(df_group)
    print()
    print()

gender

        mean  count  diff  risk
gender
Female   0.0   2796   0.0   NaN
Male     0.0   2838   0.0   NaN

seniorcitizen

               mean  count  diff  risk
seniorcitizen
0               0.0   4722   0.0   NaN
1               0.0    912   0.0   NaN

partner

         mean  count  diff  risk
partner
No        0.0   2932   0.0   NaN
Yes       0.0   2702   0.0   NaN

dependents

            mean  count  diff  risk
dependents
No           0.0   3968   0.0   NaN
Yes          0.0   1666   0.0   NaN

phoneservice

              mean  count  diff  risk
phoneservice
No             0.0    547   0.0   NaN
Yes            0.0   5087   0.0   NaN

multiplelines

                  mean  count  diff  risk
multiplelines
No                 0.0   2700   0.0   NaN
No phone service   0.0    547   0.0   NaN
Yes                0.0   2387   0.0   NaN

internetservice

                 mean  count  diff  risk
internetservice
DSL               0.0   1934   0.0   NaN
Fiber optic       0.0   2479   0.0   NaN
No                0.0   1221   0.0   NaN

onlinesecurity

                     mean  count  diff  risk
onlinesecurity
No                    0.0   2801   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1612   0.0   NaN

onlinebackup

                     mean  count  diff  risk
onlinebackup
No                    0.0   2498   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1915   0.0   NaN

deviceprotection

                     mean  count  diff  risk
deviceprotection
No                    0.0   2473   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1940   0.0   NaN

techsupport

                     mean  count  diff  risk
techsupport
No                    0.0   2781   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   1632   0.0   NaN

streamingtv

                     mean  count  diff  risk
streamingtv
No                    0.0   2246   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   2167   0.0   NaN

streamingmovies

                     mean  count  diff  risk
streamingmovies
No                    0.0   2213   0.0   NaN
No internet service   0.0   1221   0.0   NaN
Yes                   0.0   2200   0.0   NaN

contract

                mean  count  diff  risk
contract
Month-to-month   0.0   3104   0.0   NaN
One year         0.0   1186   0.0   NaN
Two year         0.0   1344   0.0   NaN

paperlessbilling

                  mean  count  diff  risk
paperlessbilling
No                 0.0   2313   0.0   NaN
Yes                0.0   3321   0.0   NaN

paymentmethod

                           mean  count  diff  risk
paymentmethod
Bank transfer (automatic)   0.0   1219   0.0   NaN
Credit card (automatic)     0.0   1217   0.0   NaN
Electronic check            0.0   1893   0.0   NaN
Mailed check                0.0   1305   0.0   NaN

In [289]:
from sklearn.metrics import mutual_info_score
mutual_info_score(df_full_train.churn, df_full_train.contract)

0.0

In [290]:
mutual_info_score(df_full_train.gender, df_full_train.churn)

0.0

In [291]:
mutual_info_score(df_full_train.partner, df_full_train.churn)

0.0

In [292]:
def mutual_info_churn_score(series):
    return mutual_info_score(series, df_full_train.churn)

In [293]:
mi = df_full_train[categorical].apply(mutual_info_churn_score)
mi.sort_values(ascending=False)

gender              0.0
seniorcitizen       0.0
partner             0.0
dependents          0.0
phoneservice        0.0
multiplelines       0.0
internetservice     0.0
onlinesecurity      0.0
onlinebackup        0.0
deviceprotection    0.0
techsupport         0.0
streamingtv         0.0
streamingmovies     0.0
contract            0.0
paperlessbilling    0.0
paymentmethod       0.0
dtype: float64

In [294]:
df_full_train[numerical].corrwith(df_full_train.churn)

d:\Python\Projects\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3036: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
d:\Python\Projects\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3037: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

tenure           NaN
monthlycharges   NaN
totalcharges     NaN
dtype: float64

In [295]:
df_full_train[numerical].corrwith(df_full_train.churn).abs()

d:\Python\Projects\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3036: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
d:\Python\Projects\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3037: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

tenure           NaN
monthlycharges   NaN
totalcharges     NaN
dtype: float64

In [296]:
df_full_train.tenure.max()

np.int64(72)

In [297]:
df_full_train[df_full_train.tenure <= 2].churn.mean()

np.float64(0.0)

In [298]:
df_full_train[(df_full_train.tenure > 2) & (df_full_train.tenure <= 12)].churn.mean()

np.float64(0.0)

In [299]:
df_full_train[df_full_train.tenure > 12].churn.mean()

np.float64(0.0)

In [300]:
df_full_train[df_full_train.monthlycharges <= 20].churn.mean()

np.float64(0.0)

In [301]:
df_full_train[(df_full_train.monthlycharges > 20) & (df_full_train.monthlycharges <= 50)].churn.mean()

np.float64(0.0)

In [302]:
df_full_train[df_full_train.monthlycharges > 50].churn.mean()

np.float64(0.0)

In [303]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression

# 1. قراءة البيانات
data_url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'
df = pd.read_csv(data_url)

# 2. تنظيف الأعمدة
df.columns = df.columns.str.lower().str.replace(' ', '_')
categorical = list(df.select_dtypes(include=['object', 'str']).columns)
for c in categorical:
    df[c] = df[c].str.lower().str.replace(' ', '_')

df['totalcharges'] = pd.to_numeric(df['totalcharges'], errors='coerce').fillna(0)
df['churn'] = (df['churn'] == 'yes').astype(int)

# 3. التقسيم (60% Train, 20% Val, 20% Test)
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

y_train = df_train['churn'].values
y_val = df_val['churn'].values
y_test = df_test['churn'].values

del df_train['churn']
del df_val['churn']
del df_test['churn']